### ISSUE TITLE
running on windows

### ISSUE THREAD

**Issue by PaulStAmand** [MitocGroup/deep-microservices-todomvc#55] opened 2016-03-10 07:12 UTC
windows 10
deep 1.7.9
node 4.4.0
npm 2.14.20

02:09:00 GMT-0500 (Eastern Standard Time)  Running Lambda arn:aws:lambda:::function:deep.ng.todo-task-retrieve with payload {}
C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-db\lib.compiled\Local\Driver\AbstractDriver.js:73
        throw error;
        ^

Error: Cannot find module '../internal/baseAssign'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:164:19)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\node_modules\aws-sdk\node_modules\xmlbuilder\node_modules\lodash\object\assign.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:164:19)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\node_modules\aws-sdk\node_modules\xmlbuilder\lib\index.js:5:12)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\node_modules\aws-sdk\node_modules\xmlbuilder\lib\index.js:14:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:164:19)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\node_modules\aws-sdk\lib\xml\builder.js:2:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:164:19)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\node_modules\aws-sdk\lib\core.js:42:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:164:19)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\node_modules\aws-sdk\lib\aws.js:1:73)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:151:36)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\lib\index.js:5:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:164:19)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\node_modules\deep-db\node_modules\vogels\index.js:3:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:164:19)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\node_modules\deep-db\lib.compiled\DB.js:25:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:164:19)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\node_modules\deep-db\lib.compiled\bootstrap.js:9:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:164:19)
    at require (internal/module.js:12:17)
    at Framework._resolveServicesMap (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\lib.compiled\Framework.js:121:24)
    at new Framework (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\lib.compiled\Framework.js:35:27)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\node_modules\deep-framework\lib.compiled\bootstrap.js:9:33)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Proxyquire._require (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:164:19)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\deep-todo-app\deep-microservices-todo-app\Backend\src\Task\Retrieve\bootstrap.js:9:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:243:43)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at Proxyquire._withoutCache (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:177:12)
    at Proxyquire.load (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\proxyquire\lib\proxyquire.js:134:15)
    at Function._createClass.value (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\lib.compiled\Lambda\Runtime.js:1:4640)
    at a._createClass.value (C:\Users\user\AppData\Roaming\npm\node_modules\deepify\lib.compiled\Server\Instance.js:1:5746)
    at C:\Users\user\AppData\Roaming\npm\node_modules\deepify\lib.compiled\Server\Instance.js:1:8095
    at C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-db\node_modules\fs-extra\node_modules\graceful-fs\graceful-fs.js:43:10
    at C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-fs\node_modules\fs-extra\node_modules\graceful-fs\graceful-fs.js:43:10
    at C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\fs-extra\node_modules\graceful-fs\graceful-fs.js:43:10
    at C:\Users\user\AppData\Roaming\npm\node_modules\deepify\node_modules\deep-package-manager\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)

user@toshiba MINGW64 ~
$

**Comment by eistrati** [comment] 2016-03-10 14:45
@PaulStAmand Usually `Error: Cannot find module` is related to broken or unfinished `npm install`. Our team recommends to make sure you install JRE v6+, `npm install aws-sdk -g` and retry everything from scratch. Let us know if you still have issues.

**Comment by PaulStAmand** [comment] 2016-03-10 16:10
Java 1.8.73 is already installed and enabled

I cleared out deepify and todo and started everything over 
windows 10
node 4.4.0
npm 3.8.0 this didn't update last time, unclear if this is at all related
deepify 1.7.9

I've reinstalled git-bash with command line integration.  Not being able to see the prompts in git-bash was causing me to question whether node was waiting for input or processing.

there was a cp error at the beginning on the deepify server deep-todo-app -o starting, but it finally did settle down and successfully launched.  it scrolled away being in CMD, I'll try to catch it in case that's something important.

I tried finding what the -o does and I've not located the code?
What does the -o do on deepify server commands?
Is that deprecated or still needed?
Working local I also noticed I have to wait for the todo adds to complete and get added to the page.  I was thinking it was stuck, but looking at the server screen, it was processing the add.

figuring out where the console prompts are going in windows 10 would go a long way toward being able to use git-bash.

**Comment by eistrati** [comment] 2016-03-10 18:06
You can ignore "-o" option. This option opens up your browser automatically on Mac OSX :)

Yes, if you can catch some of these issues, it would definitely help. But please correct me if I'm wrong, it looks like it's working now for you.

Last, but not the least, it would help us improve if you can suggest where should we add more messaging, especially steps where you've waited longer than expected. Thoughts?

**Comment by PaulStAmand** [comment] 2016-03-10 18:26
Oh, that seems to work on windows.  I noticed this morning the Frontend
launched.  Don't recall if that's recent or was always happening.

The waiting part is windows 10 not displaying the prompt while it's waiting
for the optional input in helloworld.

**Comment by PaulStAmand** [comment] 2016-03-10 18:33
I'm trying to dig in to the code to find where that prompt for input
happens. Searching why it works in the windows cmd, seems to be related to
whether the window is a true console window.  I think it's specific to
windows 10.  Still searching if others are having git bash output issues on
windows 10.

**Comment by eistrati** [comment] 2016-03-11 16:35
I have 2 updates:
1. "-o" option is an implementation of https://www.npmjs.com/package/open. Our team says that it should work on both Unix and Windows. Can you please double check that on your machine? If it doesn't, we should be able to open an issue to this repository.
2. We are not able to reproduce the prompt issue, so I apologize for not being able to help you further on this one...

Let me know if you find something that will get to the bottom of the problem.

**Comment by PaulStAmand** [comment] 2016-03-11 17:37
Yes -o works on windows.

Under Windows 7 the optional parameters are prompted for w descriptions,
under win 10 the wait for input occurs but there no indication what's being
asked for under git bash, the description of the ask does display under cmd
on win 10, but the text does appear under win 7 either w git bash or cmd.

I have node inspector running and  I'm trying to walk through the launch to
learn more about the execution steps.  I'll let you know when I figure out
where in the code the differences happen.

I have no default parameters fuels present,  if you do that might be a
difference, nor do I have env vars to accept defaults.
On Mar 11, 2016 11:35 AM, "eistrati" notifications@github.com wrote:

I have 2 updates:

   1.

   "-o" option is an implementation of https://www.npmjs.com/package/open.
   Our team says that it should work on both Unix and Windows. Can you please
   double check that on your machine? If it doesn't, we should be able to open
   an issue to this repository.
   2.

   We are not able to reproduce the prompt issue, so I apologize for not
   being able to help you further on this one...

Let me know if you find something that will get to the bottom of the
problem.

**Comment by eistrati** [comment] 2016-03-20 19:38
@PaulStAmand Any feedback? Please share if you have something useful or interesting.

**Comment by eistrati** [comment] 2016-04-05 01:02
From our latest tests, it looks like it's working. I'll close this issue now, but please feel free to reopen it if you have further problems.

**Closed as completed by eistrati** 2016-04-05 01:02 UTC
